version: "3"
services:
  chrome0:
    image: seleniarm/node-chromium:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
      - ./downloads:/home/seluser/Downloads
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    networks:
      - main_network

  seleniarm-hub:
    image: seleniarm/hub:4.0.0-beta-1-20210215
    container_name: seleniarm-hub-4.0.0-beta-1-20210215
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - main_network

  runner_downloader:
    build: .
    depends_on:
     - seleniarm-hub
    environment:
    - IS_DOCKER=True
    ports:
      - "8080:8080"
    entrypoint: [
        "./wait-for-it.sh", "-t", "20", "seleniarm-hub:4444", "--", "python3", "src/main.py"
    ]
    networks:
      - main_network
    volumes:
      - ./src:/pdf/src
      - ./conf:/pdf/conf

  huginn:
    image: huginn/huginn
    ports:
      - 3000:3000
    restart: always
    volumes:
      - huginn-data:/var/lib/mysql
    networks:
      - main_network

volumes:
  huginn-data:

networks:
  main_network:
    driver: bridge