version: "3"
services:
  hub:
    image: selenium/hub
    container_name: automation_hub
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    networks:
      - parser_network

  chrome_worker_1:
    image: selenium/node-chrome
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    networks:
      - parser_network

  runner_downloader:
    container_name: runner_downloader
    build: .
    depends_on:
     - hub
    environment:
    - IS_DOCKER=True
    networks:
      - parser_network
    entrypoint: [
        "./wait-for-it.sh", "-t", "30", "automation_hub:5555", "--", "python3", "src/main.py"
    ]

networks:
  parser_network:
    driver: bridge